### ISSUE TITLE
Cant take Photo

### ISSUE THREAD

**Issue by alexpmagalhaes** [phenotiki/raspistillWeb#2]
When I used the 0.2 version "made for phenotiki" I can't take a photo.
Timelapse still works but not the take photo.

Gives me this 

Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

and redirects to ..../photo

Taken photos being stores in /pictures

**Comment by andobrescu** [comment]
Hello @apmagalhaes,

Just to clarify there are no error messages when capturing, viewing and downloading time lapses?

According to the information you have provided, we can suggest the following possible solutions.
-Please check the settings in the web page and make sure Bisque is inactivated and try again. 
-Log into the raspberry Pi and get the following imports as they may have been not installed properly:
                 -cd ~/phenotiki/env/
                 -sudo apt-get install libxml2-dev libxslt-dev
                 -bin/pip install lxml
                 -sudo apt-get install python-dev python-setuptools
                 -sudo apt-get install pillow
                 -bin/pip install requests-toolbelt

Please, let us know whether you solved the problem or not. In the latter case, please post any error messages which are present in the raspberry pi terminal which you used to initialize the web server.

Best regards,
Andrei

**Comment by alexpmagalhaes** [comment]
Hi


All the installation steps are were done before and no errors were found.
So its not a dependency problem.

I can do all the time lapse and I have bisque turned off.

The button takes the picture and it stores it to /pictures but it redirects me to /photo.
With the original version, written for Phython3, the button works and redirect me to /pictures which are where all the taken pictures go.

Best regards

Alex

**Comment by andobrescu** [comment]
Hello,
I think I found the solution to your problem. 
Go to your raspistillweb folder ( something like ~/phenotiki/env/raspistillWeb/raspistillweb) and manualy create a folder there called 'pictures' and one called 'thumbnails'.
Delete a folder called photo if there is one present. 

The server should know to use the pictures folder but sometimes does not create it. 

Best regards,
Andrei

**Comment by alexpmagalhaes** [comment]
Hi Andrei.

It is resolved.

Thanks :)
